### PR TITLE
Framework and Platform improvements (App, Math, Graphical, Storage)

### PR DESCRIPTION
**Pull request by Techiesplash**
## Changes:
- `App` now allows passing a preferred renderer as an optional argument, defaults to Renderers.None
- `Batcher.Text()` no longer starts a new batch every whitespace character (caused many extra draw calls)
- `ShaderDefaults` has been changed to use [verbatim text](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim) (multiline) literals to improve maintainability
- Reworked `Ease`:
	- Changed the Ease class to a struct that will automatically set up `In`, `Out`, and `InOut` variants of an Easer based on one or two provided, also accepts the others being specified
	- Changed default Easers to use Ease class instead, removed variants
	- Added `Quartic` easer (t = t^4)
- Changes in OpenGL Platform implementation:
	- Fixed typo in Texture struct ("FoxtureTexure_OpenGL"?)
	- Optimizations:
		- Fixed mistake in texture binding in AssignAttributes that caused `stateTextureSlots` to not be updated (thus causing a rebind of the texture every time)
		- Now keeps track of bound `ARRAY_BUFFER` and does not rebind if matching (reduces rebind calls notably)
		- Now keeps track of bound `ELEMENT_ARRAY_BUFFER` and does not rebind if matching (reduces rebind calls notably)
	- Reformatted code:
		- `DEBUGPROC` arguments now aligned with source argument
		- `case` statements now consistently have an indent
		- Instances of `i ++` changed to `i++` for consistency

## Additions
- Content API added:
	- `Content`: Read-only file access API with default impl, virtual
	- `WritableContent`: derives from Readable, allows writing to files, also with default impl, virtual
	- `UserStorage` (static class): Accepts a WritableContent global (Creates default one at `App.UserPath`). This allows it to reuse working API, still allows overriding it for specialized access

### Ease:
```cs
// Generates Out and InOut automatically
Ease autoEase = new (t => t * t);
// Generates only InOut automatically
Ease partialAutoEase = new (t => t * t, t => t * t);
// Generates nothing automatically
Ease manual = new (t => t * t, t => t * t, t => t * t);

// And to access the Easers it creates
var i = autoEase.In(t);
var o = autoEase.Out(t);
var x = autoEase.InOut(t);

// Ease also includes an Apply function that invokes InOut, and clamps the input to 0-1
x = autoEase.Apply(t);

// Easers can still be defined and used the same
Ease.Easer linear = (float t) => t;
```

### Content:
```cs
// The Content class by default uses the default C# File/Directory API
// Assign to custom content class if desired
Content content = new Content(); 
Stream read = content.OpenRead();

// Uses the default WritableContent at directory App.UserPath
// Can be changed at UserStorage.Provider
UserStorage.WriteAllText("My Text!"); 
```

### Benchmark details:
- One million frogs via FroggyMark using the default Batcher
- Both compiled locally on `Release` configuration and linked to the benchmark via `ProjectReference`
    - NuGet packages *specifically* appear to be much faster? I was getting 30FPS on NuGet packages.
- Analyzed via [NVIDIA Nsight Graphics](https://developer.nvidia.com/nsight-graphics)

| As current (0.1.16a) | With fixes |
| ----------- | ---------- |
| Count: 276  | Count: 166 |
| FPS: ~13    | FPS: ~13   |
| Issues: 100 | Issues: 2  |
|  |  |

### CODE REVIEW

**Comment by NoelFB** [comment]
Hey, this looks quite good, thank you! Few small thoughts:
 - Can we keep the existing Ease methods, but they redirect to the new ones and include an [Obsolete] attribute? This way it wont break existing code.
 - All of the tabs were converted in `foster_renderer_opengl.c`; ideally these would be left to match the rest of the project.

**Comment by mrrpnya** [comment]
I put in obsolete-marked redirects for Easers.
Indenting seems to be fixed... There's shenanigans going on with the IDE when it comes to indents.

**Comment by NoelFB** [comment]
Awesome, this looks really great, thanks for all the fixes and additions! :)

**Comment by NoelFB** [comment]
Hmm I'm getting a `GL (ERROR:HIGH) GL_INVALID_OPERATION error generated. <texture> is not the name of an existing texture.` sometimes when I try to create a Target (Framebuffer) now in a side project of mine. Investigating, not sure if it was from these changes or something else.

**Comment by NoelFB** [comment]
Yeah the error seems to occur if I create a Target, dispose it immediately, and then create another one. It re-uses the GL ID and something bad happens in `fgl.glFramebufferTexture2D(GL_FRAMEBUFFER, tex->glAttachment, GL_TEXTURE_2D, tex->id, 0);`. Looking into it.

**Comment by NoelFB** [comment]
Fixed this - it was an issue with deleting a texture while it was bound to a slot, and now that the slot stuff is actually caching properly, it broke. Pushing a fix!

**Pull request merged**
