### PR TITLE
Added `Rect.Translate` and `RectInt.Translate`

### PR DESCRIPTION
**Pull request by codecat**
I frequently find myself needing these functions, so I figured I'd make a pull request for it. Hopefully it's useful 😊

### CODE REVIEW

**Comment by MrBrixican** [comment]
There is overloaded `+ Vector2` and `- Vector2` operators for `Rect` that already accomplish what you want, but it may be nice to have an actual method like we have for scaling. Additionally, it may not be a bad idea to have overloaded `+ Point2` and `- Point2` operators for `RectInt` as well.

**Comment by codecat** [comment]
Ah! I totally missed that! Makes sense to have named functions indeed, to make sure stuff doesn't get overlooked.

**Comment by codecat** [comment]
I've added `operator +` and `operator -` to `RectInt` for this PR as well.

**Comment by NoelFB** [comment]
Yeah I think this is fine ... I usually also use +/- operators but I think it's nice to have.

**Pull request merged**
